In [95]:
#Author: Priya Patel
#Date: 20200303
#CS301-006, Professor Watson
#HW05 Solution
#Learn how manipulate data into visualizations like bar charts, histograms and scatter plots and identify key items of these visualizations through descriptions and critiques.
#https://github.com/priyapatell/CS301.git
#master

In [96]:
import pandas as pd
import numpy as py

##Visualization Libraries
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

## Homework 06

#### Question 1 - Read in the data set and print the % empty values for each column. Are there any columns with missing values?

In [127]:
data_dir= '/Users/pdpat/Documents/CS301 Folder/groundhog.csv'
df= pd.read_csv(data_dir)
df= df.drop(columns=['Unnamed: 0'])

for col in df.columns:
    total= df.shape[0]
    num= df.loc[df[col].isna()]
    empty= num.shape[0]
    percent= (empty/total)*100
    print('The \"{}\" column has {:.2f}% or {:.0f} empty values'.format(col, percent, empty))

print('\nThere are 8 columns that are each missing 6.87% of values.')

df

The "Year" column has 0.00% or 0 empty values
The "Punxsutawney Phil" column has 0.00% or 0 empty values
The "February Average Temperature" column has 6.87% or 9 empty values
The "February Average Temperature (Northeast)" column has 6.87% or 9 empty values
The "February Average Temperature (Midwest)" column has 6.87% or 9 empty values
The "February Average Temperature (Pennsylvania)" column has 6.87% or 9 empty values
The "March Average Temperature" column has 6.87% or 9 empty values
The "March Average Temperature (Northeast)" column has 6.87% or 9 empty values
The "March Average Temperature (Midwest)" column has 6.87% or 9 empty values
The "March Average Temperature (Pennsylvania)" column has 6.87% or 9 empty values

There are 8 columns that are each missing 6.87% of values.


Year Punxsutawney Phil  February Average Temperature  \
0    1886         No Record                           NaN   
1    1887       Full Shadow                           NaN   
2    1888       Full Shadow                           NaN   
3    1889         No Record                           NaN   
4    1890         No Shadow                           NaN   
..    ...               ...                           ...   
126  2012       Full Shadow                         37.51   
127  2013         No Shadow                         34.77   
128  2014       Full Shadow                         32.13   
129  2015       Full Shadow                         32.99   
130  2016         No Shadow                         39.47   

     February Average Temperature (Northeast)  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                         NaN   
4                                         NaN   
..                                        ...   
126                                      30.6   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   

     February Average Temperature (Midwest)  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
..                                      ...   
126                                    38.6   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
0                                            NaN                        NaN   
1                                            NaN                        NaN   
2                                            NaN                        NaN   
3                                            NaN                        NaN   
4                                            NaN                        NaN   
..                                           ...                        ...   
126                                         34.3                      50.41   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   

     March Average Temperature (Northeast)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                      NaN   
4                                      NaN   
..                                     ...   
126                                   43.4   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   

     March Average Temperature (Midwest)  \
0                                    NaN   
1                                    NaN   
2                                    NaN   
3                                    NaN   
4                                    NaN   
..                                   ...   
126                                 56.3   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   

     March Average Temperature (Pennsylvania)  
0                                      

#### Question 2 - Create a new dataframe which is a copy of the orginal one. In this copy, replace the missing values in the data set using one of the discussed methods in class.

In [128]:
copy= df
means= df.mean(axis = 0, skipna = True)
print('The means of each colomn were:\n')
print(means)

i=-1;
for col in copy.columns:
    i+=1
    if i >=2:
        k= means[i-1]
        for j in range(9):
            copy.at[j, col]= round(k,2)

copy

The means of each colomn were:

Year                                           1951.000000
February Average Temperature                     33.802705
February Average Temperature (Northeast)         22.693443
February Average Temperature (Midwest)           32.694262
February Average Temperature (Pennsylvania)      26.522951
March Average Temperature                        41.699016
March Average Temperature (Northeast)            32.368033
March Average Temperature (Midwest)              42.568852
March Average Temperature (Pennsylvania)         35.908197
dtype: float64


Year Punxsutawney Phil  February Average Temperature  \
0    1886         No Record                         33.80   
1    1887       Full Shadow                         33.80   
2    1888       Full Shadow                         33.80   
3    1889         No Record                         33.80   
4    1890         No Shadow                         33.80   
..    ...               ...                           ...   
126  2012       Full Shadow                         37.51   
127  2013         No Shadow                         34.77   
128  2014       Full Shadow                         32.13   
129  2015       Full Shadow                         32.99   
130  2016         No Shadow                         39.47   

     February Average Temperature (Northeast)  \
0                                       22.69   
1                                       22.69   
2                                       22.69   
3                                       22.69   
4                                       22.69   
..                                        ...   
126                                     30.60   
127                                     25.30   
128                                     21.00   
129                                     12.10   
130                                     28.10   

     February Average Temperature (Midwest)  \
0                                     32.69   
1                                     32.69   
2                                     32.69   
3                                     32.69   
4                                     32.69   
..                                      ...   
126                                   38.60   
127                                   33.40   
128                                   27.10   
129                                   23.40   
130                                   36.90   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
0                                          26.52                      41.70   
1                                          26.52                      41.70   
2                                          26.52                      41.70   
3                                          26.52                      41.70   
4                                          26.52                      41.70   
..                                           ...                        ...   
126                                        34.30                      50.41   
127                                        27.40                      40.91   
128                                        22.80                      40.51   
129                                        16.10                      45.39   
130                                        30.80                      47.50   

     March Average Temperature (Northeast)  \
0                                    32.37   
1                                    32.37   
2                                    32.37   
3                                    32.37   
4                                    32.37   
..                                     ...   
126                                  43.40   
127                                  32.70   
128                                  26.00   
129                                  27.80   
130                                  38.80   

     March Average Temperature (Midwest)  \
0                                  42.57   
1                                  42.57   
2                                  42.57   
3                                  42.57   
4                                  42.57   
..                                   ...   
126                                56.30   
127                                37.30   
128                                38.00   
129                                41.60   
130                                49.50   

     March Average Temperature (Pennsylvania)  
0                                      

#### Question 3 - Is your proposed method from Question 2 appropriate in this case? Why or why not?

For question 2, I used the method discussed in class where empty values are substituted with the mean or average of the rest of the values in that respective column. I do not think this method is appropriate for this case because it disregards any potential trends of increasing or decreasing temperature that may be occuring over time.

#### Question 4 - Using the original dataframe (unchanged from Questoins 2, 3), create a mapping for the "Punxsutawney Phil" column which changes the categories into numerical quantities. For example: 'No Record' can be 0, 'No Shadow' can be 1, 'Partial Shadow' can be 2, and 'Full Shadow' can be 3. You should create the mapping *and* apply it to the data set by adding a new column called "Shadow".

In [99]:
df['Shadow']=''
for i in range(df.shape[0]):
    cat= df['Punxsutawney Phil'].iloc[i]
    if cat == 'No Record':
        df.at[i, 'Shadow']= 0
    if cat == 'No Shadow':
        df.at[i, 'Shadow']= 1
    if cat == 'Partial Shadow':
        df.at[i, 'Shadow']= 2
    if cat == 'Full Shadow':
        df.at[i, 'Shadow']= 3
        
df


Year Punxsutawney Phil  February Average Temperature  \
0    1886         No Record                           NaN   
1    1887       Full Shadow                           NaN   
2    1888       Full Shadow                           NaN   
3    1889         No Record                           NaN   
4    1890         No Shadow                           NaN   
..    ...               ...                           ...   
126  2012       Full Shadow                         37.51   
127  2013         No Shadow                         34.77   
128  2014       Full Shadow                         32.13   
129  2015       Full Shadow                         32.99   
130  2016         No Shadow                         39.47   

     February Average Temperature (Northeast)  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                         NaN   
4                                         NaN   
..                                        ...   
126                                      30.6   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   

     February Average Temperature (Midwest)  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
..                                      ...   
126                                    38.6   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
0                                            NaN                        NaN   
1                                            NaN                        NaN   
2                                            NaN                        NaN   
3                                            NaN                        NaN   
4                                            NaN                        NaN   
..                                           ...                        ...   
126                                         34.3                      50.41   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   

     March Average Temperature (Northeast)  \
0                                      NaN   
1                                      NaN   
2                                      NaN   
3                                      NaN   
4                                      NaN   
..                                     ...   
126                                   43.4   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   

     March Average Temperature (Midwest)  \
0                                    NaN   
1                                    NaN   
2                                    NaN   
3                                    NaN   
4                                    NaN   
..                                   ...   
126                                 56.3   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   

     March Average Temperature (Pennsylvania) Shadow  
0                               

#### Question 5 - For all rows which have no record, remove the rows which have empty values in all of the quantitative columns. (Only 6 should be removed.)

In [100]:
norec= df.loc[df['Shadow']==0]
rows= norec.index[norec['February Average Temperature'].isna()].tolist()
print(rows)

df= df.drop(df.index[[0,3,5,6,7,8]])
df

[0, 3, 5, 6, 7, 8]


Year Punxsutawney Phil  February Average Temperature  \
1    1887       Full Shadow                           NaN   
2    1888       Full Shadow                           NaN   
4    1890         No Shadow                           NaN   
9    1895         No Record                         26.60   
10   1896         No Record                         35.04   
..    ...               ...                           ...   
126  2012       Full Shadow                         37.51   
127  2013         No Shadow                         34.77   
128  2014       Full Shadow                         32.13   
129  2015       Full Shadow                         32.99   
130  2016         No Shadow                         39.47   

     February Average Temperature (Northeast)  \
1                                         NaN   
2                                         NaN   
4                                         NaN   
9                                        15.6   
10                                       22.2   
..                                        ...   
126                                      30.6   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   

     February Average Temperature (Midwest)  \
1                                       NaN   
2                                       NaN   
4                                       NaN   
9                                      21.9   
10                                     33.5   
..                                      ...   
126                                    38.6   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
1                                            NaN                        NaN   
2                                            NaN                        NaN   
4                                            NaN                        NaN   
9                                           17.0                      39.97   
10                                          26.6                      38.03   
..                                           ...                        ...   
126                                         34.3                      50.41   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   

     March Average Temperature (Northeast)  \
1                                      NaN   
2                                      NaN   
4                                      NaN   
9                                     27.6   
10                                    25.3   
..                                     ...   
126                                   43.4   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   

     March Average Temperature (Midwest)  \
1                                    NaN   
2                                    NaN   
4                                    NaN   
9                                   40.2   
10                                  36.9   
..                                   ...   
126                                 56.3   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   

     March Average Temperature (Pennsylvania) Shadow  
1                               

#### Question 6 - For the remaining rows which have no record (but the other columns *are* populated), determine an appropriate method for inputting the value for this column. Explain your reasoning, and show your work below (using pandas).

In [101]:
#df.median(axis = 0, skipna = True)
#norec= df.loc[df['Shadow']==0]
#for i in range(norec.shape[0]):
#    df.at[i,'Shadow']= 3
#    
df

Year Punxsutawney Phil  February Average Temperature  \
1    1887       Full Shadow                           NaN   
2    1888       Full Shadow                           NaN   
4    1890         No Shadow                           NaN   
9    1895         No Record                         26.60   
10   1896         No Record                         35.04   
..    ...               ...                           ...   
126  2012       Full Shadow                         37.51   
127  2013         No Shadow                         34.77   
128  2014       Full Shadow                         32.13   
129  2015       Full Shadow                         32.99   
130  2016         No Shadow                         39.47   

     February Average Temperature (Northeast)  \
1                                         NaN   
2                                         NaN   
4                                         NaN   
9                                        15.6   
10                                       22.2   
..                                        ...   
126                                      30.6   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   

     February Average Temperature (Midwest)  \
1                                       NaN   
2                                       NaN   
4                                       NaN   
9                                      21.9   
10                                     33.5   
..                                      ...   
126                                    38.6   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
1                                            NaN                        NaN   
2                                            NaN                        NaN   
4                                            NaN                        NaN   
9                                           17.0                      39.97   
10                                          26.6                      38.03   
..                                           ...                        ...   
126                                         34.3                      50.41   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   

     March Average Temperature (Northeast)  \
1                                      NaN   
2                                      NaN   
4                                      NaN   
9                                     27.6   
10                                    25.3   
..                                     ...   
126                                   43.4   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   

     March Average Temperature (Midwest)  \
1                                    NaN   
2                                    NaN   
4                                    NaN   
9                                   40.2   
10                                  36.9   
..                                   ...   
126                                 56.3   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   

     March Average Temperature (Pennsylvania) Shadow  
1                               

#### Question 7 - If we are trying to write a machine learning program which predicts the type of shadow for the year, which column(s) should be the independent variables X? Why? 

#### Use pandas to assign a variable X to be all of the rows of the data set with the column(s) that represent the independent variables.

I would have the independent variable X  be the data set with columns Year, February Average Temperature, February Average Temperature (Northeast), February Average Temperature (Midwest), February Average Temperature (Pennsylvania), March Average Temperature, March Average Temperature (Northeast), March Average Temperature (Midwest), and March Average Temperature (Pennsylvania).

In [102]:
X= df.drop(columns=['Punxsutawney Phil','Shadow'])
X

Year  February Average Temperature  \
1    1887                           NaN   
2    1888                           NaN   
4    1890                           NaN   
9    1895                         26.60   
10   1896                         35.04   
..    ...                           ...   
126  2012                         37.51   
127  2013                         34.77   
128  2014                         32.13   
129  2015                         32.99   
130  2016                         39.47   

     February Average Temperature (Northeast)  \
1                                         NaN   
2                                         NaN   
4                                         NaN   
9                                        15.6   
10                                       22.2   
..                                        ...   
126                                      30.6   
127                                      25.3   
128                                      21.0   
129                                      12.1   
130                                      28.1   

     February Average Temperature (Midwest)  \
1                                       NaN   
2                                       NaN   
4                                       NaN   
9                                      21.9   
10                                     33.5   
..                                      ...   
126                                    38.6   
127                                    33.4   
128                                    27.1   
129                                    23.4   
130                                    36.9   

     February Average Temperature (Pennsylvania)  March Average Temperature  \
1                                            NaN                        NaN   
2                                            NaN                        NaN   
4                                            NaN                        NaN   
9                                           17.0                      39.97   
10                                          26.6                      38.03   
..                                           ...                        ...   
126                                         34.3                      50.41   
127                                         27.4                      40.91   
128                                         22.8                      40.51   
129                                         16.1                      45.39   
130                                         30.8                      47.50   

     March Average Temperature (Northeast)  \
1                                      NaN   
2                                      NaN   
4                                      NaN   
9                                     27.6   
10                                    25.3   
..                                     ...   
126                                   43.4   
127                                   32.7   
128                                   26.0   
129                                   27.8   
130                                   38.8   

     March Average Temperature (Midwest)  \
1                                    NaN   
2                                    NaN   
4                                    NaN   
9                                   40.2   
10                                  36.9   
..                                   ...   
126                                 56.3   
127                                 37.3   
128                                 38.0   
129                                 41.6   
130                                 49.5   

     March Average Temperature (Pennsylvania)  
1                                         NaN  
2                                         NaN  
4                                         NaN  
9                                        31.3  
10                                       27.8  
..             

#### Question 8 - If we are trying to write a machine learning program which predicts the type of shadow for the year, which column(s) should be the dependent variables Y? Why?  

#### Use pandas to assign a variable Y to be all of the rows of the data set with the column(s) that represent the dependent variables.

I would have the dependent variable Y be the data set with columns Punxsutawney Phil and Shadow.

In [103]:
Y= df.drop(columns=['Year', 'February Average Temperature', 'February Average Temperature (Northeast)', 'February Average Temperature (Midwest)', 'February Average Temperature (Pennsylvania)', 'March Average Temperature', 'March Average Temperature (Northeast)', 'March Average Temperature (Midwest)', 'March Average Temperature (Pennsylvania)'])
Y

Punxsutawney Phil Shadow
1         Full Shadow      3
2         Full Shadow      3
4           No Shadow      1
9           No Record      0
10          No Record      0
..                ...    ...
126       Full Shadow      3
127         No Shadow      1
128       Full Shadow      3
129       Full Shadow      3
130         No Shadow      1

[125 rows x 2 columns]

#### Question 9 - Using the train_test_split function from the sklearn module, use a 70/30 split validation to split the data set into train and test. If you follow the example at the following link: https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

Note: It's common practice to use the following variable names for unpacking the result:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=(YOUR VALUE))

sklearn will create a proper split where the following statements hold true:
X_train is your train set independent variables
Y_train is your train set dependent variables
X_test is your test set independent variables
Y_test is your test set dependent variables

In [72]:
from sklearn.model_selection import train_test_split

In [126]:
X, Y = py.arange(1375).reshape((125, 11)), range(125)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=None)
print(X_test)

[[ 517  518  519  520  521  522  523  524  525  526  527]
 [1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231]
 [ 264  265  266  267  268  269  270  271  272  273  274]
 [ 847  848  849  850  851  852  853  854  855  856  857]
 [ 429  430  431  432  433  434  435  436  437  438  439]
 [1133 1134 1135 1136 1137 1138 1139 1140 1141 1142 1143]
 [ 330  331  332  333  334  335  336  337  338  339  340]
 [ 759  760  761  762  763  764  765  766  767  768  769]
 [ 528  529  530  531  532  533  534  535  536  537  538]
 [ 341  342  343  344  345  346  347  348  349  350  351]
 [ 495  496  497  498  499  500  501  502  503  504  505]
 [ 176  177  178  179  180  181  182  183  184  185  186]
 [ 825  826  827  828  829  830  831  832  833  834  835]
 [1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264]
 [ 891  892  893  894  895  896  897  898  899  900  901]
 [ 220  221  222  223  224  225  226  227  228  229  230]
 [1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363]
 [ 968  969  9

Since it is a large amount of data, I did not display each data set but they can easily be seen.

#### Question 10 - Should the number of rows in X_train == number of rows in Y_train? Also, should the number of rows in X_test == Y_test? Why or why not? Validate your answer with code below:

The number of rows in X_train should be equal to the number of rows in Y_train. The number of rows in X_test should also equal the number of rows in Y_train. The is validated in the code below.

In [124]:
print('The number of rows in X_train is {:.0f}.'.format(len(X_train)))
print('The number of rows in Y_train is {:.0f}.'.format(len(Y_train)))
print('The number of rows in X_test is {:.0f}.'.format(len(X_test)))
print('The number of rows in Y_test is {:.0f}.'.format(len(Y_test)))

The number of rows in X_train is 87.
The number of rows in Y_train is 87.
The number of rows in X_test is 38.
The number of rows in Y_test is 38.
